services:
  postgres:
    image: postgres:15-alpine
    restart: unless-stopped
    env_file: .env
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      DB_PORT: ${DB_PORT}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - ${DB_PORT}:${DB_PORT}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - pern-network

  redis:
    image: redis:7-alpine
    restart: unless-stopped
    env_file: .env
    environment:
      REDIS_URL: ${REDIS_URL}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}
    volumes:
    - redis-data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - pern-network

  server:
    image: node:22-bullseye-slim
    restart: unless-stopped
    command: > 
      sh -c "
        corepack enable && 
        corepack prepare pnpm@9.8.0 --activate && 
        cd /workspace && 
        pnpm install && 
        pnpm --filter @pern-auth/server prisma:generate &&
        pnpm --filter @pern-auth/server prisma:migrate:deploy &&
        pnpm --filter @pern-auth/server dev
      "
    working_dir: /workspace
    env_file: .env
    volumes:
      - ./:/workspace
      - ./.env:/workspace/.env
    environment:
      DATABASE_URL: ${DB_URL}
      REDIS_URL: ${REDIS_URL}
      JWT_SECRET: ${JWT_SECRET}
      SERVER_PORT: ${SERVER_PORT}
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - pern-network

  client:
    image: node:22-alpine
    restart: unless-stopped
    command: sh -c "corepack enable && corepack prepare pnpm@9.8.0 --activate && cd /workspace && pnpm install && pnpm --filter @pern-auth/client dev -- --host 0.0.0.0"
    working_dir: /workspace
    env_file: .env
    environment:
      API_BASE_URL: ${API_BASE_URL}
      CLIENT_PORT: ${CLIENT_PORT}
    volumes:
      - ./:/workspace
      - ./.env:/workspace/.env
    ports:
      - ${CLIENT_PORT}:${CLIENT_PORT}
    depends_on:
      - server
    networks:
      - pern-network
      
  nginx:
    image: nginx:stable-alpine
    restart: unless-stopped
    env_file: .env
    environment:
      SERVER_URL: ${SERVER_URL}
      CLIENT_URL: ${CLIENT_URL}
      NGINX_PORT: ${NGINX_PORT}
    ports:
      - ${NGINX_PORT}:${NGINX_PORT}
    volumes:
      - ./nginx/nginx.conf.template:/etc/nginx/templates/default.conf.template:ro
    depends_on:
      - client
      - server
    networks:
      - pern-network

volumes:
  postgres-data:
  redis-data:

networks:
  pern-network:
    driver: bridge