auth:
  username: admin
  password: console
  database: pernforge

primary:
  persistence:
    enabled: true
    size: 1Gi
    storageClass: standard

  resources:
    requests:
      memory: "256Mi"
      cpu: "250m"
    limits:
      memory: "512Mi"
      cpu: "500m"

  livenessProbe:
    enabled: true

  readinessProbe:
    enabled: true