apiVersion: v1
kind: Secret

metadata:
  name: pernforge-secret

type: Opaque

stringData:
  DATABASE_URL: postgresql://admin:console@postgres-postgresql:5432/pernforge

  REDIS_URL: redis://:pernforge@redis-master:6379

  JWT_SECRET: pernforge