apiVersion: v1
kind: Secret

metadata:
  name: pernforge-secret

type: Opaque

stringData:
  DATABASE_URL: postgresql://postgres:xRyqHV2UFO@postgres-postgresql:5432/pernforge

  REDIS_URL: redis://:MOspR7XJ5K@redis-master:6379

  JWT_SECRET: pernforge