apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: pernforge-prod

resources:
  - ../../base

images:
  - name: pernforg-server
    newName: nilrajpurohit3/pern-server
    newTag: latest

  - name: pernforg-client
    newName: nilrajpurohit3/pern-client
    newTag: latest